name: Build NPM Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build package
        run: npm run build
      
      - name: Publish to NPM
        uses: js-actions/npm@v1
        with:
          args: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
